# Copyright 2025 Danknight
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[project]
authors = ["Danknight <https://github.com/rgantonio>"]
channels = ["conda-forge","kuleuven-micas"]
description = "A heterogeneous accelerator-centric compute cluster"
name = "digiforge"
platforms = ["linux-64"]
version = "0.0.1"

[tasks]

[dependencies]
python = ">=3.12.0,<3.13"
verilator = ">=5.30,<6"
make = ">=4.4.1,<5"
clang = ">=19.1.7,<20"
clangxx = ">=19.1.7,<20"
lld = ">=19.1.7,<20"
pandas = ">=2.2.3,<3"
jsonref = ">=1.1.0,<2"
jsonschema = ">=4.23.0,<5"
mako = ">=1.3.8,<2"
pyyaml = ">=6.0.2,<7"
termcolor = ">=2.5.0,<3"
pyelftools = ">=0.31,<0.32"
psutil = ">=6.1.1,<7"
sbt = ">=1.10.2,<2"
dtc = ">=1.7.2,<2"
gcc_linux-64 = ">=14.2.0,<15"
gxx_linux-64 = ">=14.2.0,<15"
gcc = ">=14.2.0,<14.3"
gxx = ">=14.2.0,<14.3"
binutils = ">=2.43,<3"
boost = ">=1.84.0,<2"
boost-cpp = ">=1.84.0,<2"
tabulate = ">=0.9.0,<0.10"
setuptools = ">=75.8.0,<76"
llvm-tools = ">=19.1.7,<20"
bender = ">=0.28.2,<0.29"
hjson-py = ">=3.1.0,<4"
clang-format = ">=19.1.7,<20"
wget = ">=1.21.4,<2"
pip = ">=25.0.1,<26"

[activation.env]
VLT_ROOT = "${CONDA_PREFIX}/share/verilator"